List<String> productManagementTerms = [
  "Product",
  "Product Manager (PM)",
  "Roadmap",
  "User Story",
  "MVP (Minimum Viable Product)",
  "Feature",
  "Sprint",
  "Backlog",
  "Stakeholder",
  "Feedback",
  "KPI (Key Performance Indicator)",
  "Market Research",
  "User Persona",
  "Customer Journey",
  "A/B Testing",
  "Product Lifecycle",
  "Agile",
  "Scrum",
  "Product Owner",
  "Customer Development",
  "Lean Product",
  "Product Strategy",
  "Product Development",
  "Product Design",
  "Product Launch",
  "Product Metrics",
  "Product Requirements",
  "User Experience (UX)",
  "User Interface (UI)",
  "Competitor Analysis",
  "Product-Market Fit",
  "Feature Prioritization",
  "Release Management",
  "Product Vision",
  "Product Prototype",
  "Usability Testing",
  "Cross-Functional Team",
  "Product Backlog Grooming",
  "Churn Rate",
  "User Retention",
  "Feature Creep",
  "Beta Testing",
  "Product Enhancement",
  "Customer Segmentation",
  "Product Portfolio",
  "Product Evangelist",
  "Customer Support",
  "Product Scaling",
  "Product Testing",
  "Product Differentiation",
  "Product Innovation",
  "Product Pricing",
  "Product Revenue",
  "Product Marketability",
  "Product Launch Plan",
  "Product Validation",
  "Product Goals",
  "Product User Base",
  "Product Monetization",
  "Product Market Analysis",
  "Product ROI (Return on Investment)",
  "Product Strategy Alignment",
  "Product Maintenance",
  "Product Dependency",
  "Product Integration",
  "Product Feedback Loop",
  "Product Decision-Making",
  "Product Evolution",
  "Product Features Matrix",
  "Product Requirements Document (PRD)",
  "Product Release Cycle",
  "Product Design Sprint",
  "Product Ownership",
  "Product Delivery",
  "Product User Research",
  "Product Analytics",
  "Product Communication",
  "Product Innovation Lab",
  "Product Discovery",
  "Product Planning",
  "Product Roadmap Alignment",
  "Product Market Entry",
  "Product Scaling Strategy",
  "Product Security",
  "Product Prototyping",
  "Product Launch Strategy",
  "Product Launch Checklist",
  "Product User Onboarding",
  "Product User Engagement",
  "Product Usability",
  "Product Decision Framework",
  "Product Risk Management",
  "That's interesting, tell me more about",
  "I'd like to hear your thoughts on",
  "Can you elaborate on",
  "What other information can you provide regarding",
  "Let's explore this topic further",
  "Please go on",
  "Continue with",
  "I'm curious about",
  "What's your take on",
  "Feel free to share more about",
  "Could you provide more details on",
  "I'd love to dive deeper into",
  "This is fascinating, can you expand on",
  "I'm intrigued, can you explain",
  "How did you come to that conclusion",
  "What led you to that perspective",
  "Share your insights on",
  "Tell me your perspective on",
  "What's the backstory behind",
  "I'm eager to learn more about",
  "Could you shed more light on",
  "What's your experience with",
  "Let's dig a little deeper into",
  "I'm interested in your take on",
  "What are the key points to highlight about",
  "Can you break it down further",
  "I'd like to gain a better understanding of",
  "Share your expertise on",
  "What can you tell me about",
  "Let's unravel this topic",
  "I'd appreciate more context on",
  "What's the significance of",
  "Can you provide examples related to",
  "I'm keen to know more about",
  "Give me more details regarding",
  "Could you expand on the aspect of",
  "I'd like to explore this concept in depth",
  "What's the background information for",
  "Can you go into more detail about",
  "How does this relate to",
  "Let's focus on",
  "I'd like to hear your perspective regarding",
  "What's the connection between",
  "I'm interested in the implications of",
  "Let's analyze",
  "What are your thoughts on the impact of",
  "Can you draw parallels between",
  "I'd love to get your insights on",
  "continue",
  "more",
  "above",
  "explain",
  "lists",
  "That's interesting, tell me more about",
  "I'd like to hear your thoughts on",
  "Can you elaborate on",
  "What other information can you provide regarding",
  "Let's explore this topic further",
  "Please go on",
  "Continue with",
  "I'm curious about",
  "What's your take on",
  "Feel free to share more about",
  "Could you provide more details on",
  "I'd love to dive deeper into",
  "This is fascinating, can you expand on",
  "I'm intrigued, can you explain",
  "How did you come to that conclusion",
  "What led you to that perspective",
  "Share your insights on",
  "Tell me your perspective on",
  "What's the backstory behind",
  "I'm eager to learn more about",
  "Could you shed more light on",
  "What's your experience with",
  "Let's dig a little deeper into",
  "I'm interested in your take on",
  "What are the key points to highlight about",
  "Can you break it down further",
  "I'd like to gain a better understanding of",
  "Share your expertise on",
  "What can you tell me about",
  "Let's unravel this topic",
  "I'd appreciate more context on",
  "What's the significance of",
  "Can you provide examples related to",
  "I'm keen to know more about",
  "Give me more details regarding",
  "Could you expand on the aspect of",
  "I'd like to explore this concept in depth",
  "What's the background information for",
  "Can you go into more detail about",
  "How does this relate to",
  "Let's focus on",
  "I'd like to hear your perspective regarding",
  "What's the connection between",
  "I'm interested in the implications of",
  "Let's analyze",
  "What are your thoughts on the impact of",
  "Can you draw parallels between",
  "I'd love to get your insights on",
  "Share your knowledge about",
  "What can you tell me about the history of",
  "Let's uncover the significance of",
  "What's the relevance of",
  "How would you summarize",
  "Can you provide an overview of",
  "I'd like to know more about the role of",
  "What's the relationship between",
  "Can you discuss the importance of",
  "Let's delve into the details of",
  "I'd appreciate a breakdown of",
  "Tell me more about the context of",
  "What led to the development of",
  "I'm curious about the key features of",
  "What's your opinion on",
  "Can you provide insights into",
  "I'd like to explore the implications of",
  "What are the main points to consider for",
  "Let's evaluate the significance of",
  "I'd like to gain clarity on",
  "What's the correlation between",
  "Can you elaborate on the benefits of",
  "I'm interested in the factors affecting",
  "What's the impact of",
  "Let's assess the advantages of",
  "I'd like to understand the relationship between",
  "What's your perspective on the future of",
  "Can you provide examples of",
  "I'm keen to know more about the challenges in",
  "What's the potential for",
  "Let's explore the opportunities in",
  "I'd appreciate your insights on",
  "Tell me more about the advantages of",
  "What's the significance of innovation in",
  "Can you elaborate on the role of technology in",
  "I'm curious about the trends in",
  "What's your vision for",
  "Let's discuss the implications of sustainability in",
  "I'd like to know more about the impact of globalization on",
  "What's the future outlook for",
  "Can you provide insights into the challenges faced by",
  "I'm interested in the strategies for",
  "What's your take on the role of leadership in",
  "Let's analyze the impact of digital transformation on",
  "I'd like to explore the best practices for",
  "Tell me more about the importance of diversity in",
  "What's the connection between ethics and",
  "Can you elaborate on the role of data analytics in",
  "I'm keen to understand the relationship between customer experience and",
  "What's your perspective on the future of work in",
  "Let's explore the trends shaping the future of",
  "I'd appreciate insights on the challenges and opportunities in",
  "What's the potential for innovation in",
  "Can you discuss the implications of artificial intelligence on",
  "I'm interested in the strategies for sustainable growth in",
  "Explain",
];
