List<String> productManagementPrompts = [
  "Outline a step-by-step process for developing a new product from ideation to launch.",
  "Discuss the importance of market research in shaping a product's features and strategy.",
  "Explain the concept of a Minimum Viable Product (MVP) and its role in product development.",
  "Describe the key differences between waterfall and agile product development methodologies.",
  "Analyze a successful product launch and identify the factors that contributed to its success.",
  "Explore the challenges of managing a remote or distributed product team.",
  "Discuss the role of a product manager in prioritizing features and managing the product roadmap.",
  "Examine the concept of user personas and their significance in product design.",
  "Share your insights on conducting effective customer interviews to gather feedback.",
  "Compare and contrast A/B testing and usability testing in the context of product optimization.",
  "Explain the concept of a 'pivot' in product development and provide examples.",
  "Discuss the ethical considerations in product management, especially related to user data and privacy.",
  "Analyze the impact of emerging technologies (e.g., AI, blockchain) on product management strategies.",
  "Explore strategies for managing and prioritizing technical debt in a product.",
  "Describe the product manager's role in defining and measuring key performance indicators (KPIs).",
  "Discuss the significance of user retention and churn rate in evaluating a product's success.",
  "Examine the relationship between product management and user experience (UX) design.",
  "Share your insights on handling feature requests and feedback from both internal and external stakeholders.",
  "Discuss the challenges and benefits of incorporating user feedback into the product development process.",
  "Explain the role of a product manager in creating a product's pricing strategy."
];
